#pragma once

// Resources
#include "resource/AGPUBuffer.hpp"
#include "resource/ARenderPass.hpp"
#include "resource/BindGroup.hpp"
#include "resource/BindGroupManager.hpp"
#include "resource/Context.hpp"
#include "resource/DeviceContext.hpp"
#include "resource/GPUBufferContainer.hpp"
#include "resource/GraphicSettings.hpp"
#include "resource/Image.hpp"
#include "resource/Limits.hpp"
#include "resource/RenderGraph.hpp"
#include "resource/RenderGraphContainer.hpp"
#include "resource/Sampler.hpp"
#include "resource/SamplerContainer.hpp"
#include "resource/Shader.hpp"
#include "resource/ShaderContainer.hpp"
#include "resource/ShaderDescriptor.hpp"
#include "resource/SingleExecutionRenderPass.hpp"
#include "resource/Surface.hpp"
#include "resource/Texture.hpp"
#include "resource/TextureContainer.hpp"

// Utils
#include "utils/DefaultSampler.hpp"
#include "utils/DefaultTexture.hpp"
#include "utils/EmptyTexture.hpp"
#include "utils/GetBytesPerPixel.hpp"
#include "utils/IValidable.hpp"
#include "utils/shader/ABindGroupLayoutEntry.hpp"
#include "utils/shader/BindGroupLayout.hpp"
#include "utils/shader/BufferBindGroupLayoutEntry.hpp"
#include "utils/shader/ColorTargetState.hpp"
#include "utils/shader/DepthStencilState.hpp"
#include "utils/shader/IBindGroupLayoutEntry.hpp"
#include "utils/shader/SamplerBindGroupLayoutEntry.hpp"
#include "utils/shader/TextureBindGroupLayoutEntry.hpp"
#include "utils/shader/VertexBufferLayout.hpp"

// Exceptions
#include "exception/AdapterCreationError.hpp"
#include "exception/BindGroupCreationError.hpp"
#include "exception/CapabilitiesRequestError.hpp"
#include "exception/DeviceCreationError.hpp"
#include "exception/DuplicatedVertexAttributeLocationError.hpp"
#include "exception/FailToCreateCommandEncoderError.hpp"
#include "exception/FileReadingError.hpp"
#include "exception/InstanceCreationError.hpp"
#include "exception/MissingOutputRenderPassError.hpp"
#include "exception/QueueCreationError.hpp"
#include "exception/RenderPassSortError.hpp"
#include "exception/SurfaceCreationError.hpp"
#include "exception/UncapturedDeviceError.hpp"
#include "exception/UnknownFileError.hpp"
#include "exception/UnknownFormatType.hpp"
#include "exception/UnsetAttributeTextureDescriptor.hpp"
#include "exception/UnsupportedTextureFormatError.hpp"
#include "exception/UpdateBufferError.hpp"
#include "exception/VertexAttributeOverlappingError.hpp"

// Plugin
#include "plugin/PluginGraphic.hpp"

// Systems
#include "system/initialization/ConfigureSurface.hpp"
#include "system/initialization/CreateAdapter.hpp"
#include "system/initialization/CreateDefaultSampler.hpp"
#include "system/initialization/CreateDefaultTexture.hpp"
#include "system/initialization/CreateDevice.hpp"
#include "system/initialization/CreateEmptyTexture.hpp"
#include "system/initialization/CreateInstance.hpp"
#include "system/initialization/CreateQueue.hpp"
#include "system/initialization/CreateSurface.hpp"
#include "system/initialization/ReleaseAdapter.hpp"
#include "system/initialization/ReleaseInstance.hpp"
#include "system/initialization/RequestCapabilities.hpp"
#include "system/initialization/SetupQueue.hpp"
#include "system/initialization/SetupResizableRenderTexture.hpp"

#include "system/preparation/PrepareEndRenderTexture.hpp"

#include "system/commandCreation/ExecuteRenderPass.hpp"

#include "system/presentation/Present.hpp"

#include "system/shutdown/ReleaseBindingGroup.hpp"
#include "system/shutdown/ReleaseContext.hpp"
#include "system/shutdown/ReleaseGPUBuffer.hpp"
#include "system/shutdown/ReleaseSampler.hpp"
#include "system/shutdown/ReleaseShader.hpp"
#include "system/shutdown/ReleaseTexture.hpp"
