includes("../../tools/xmake/library.lua")

target("RustLib")
    set_kind("shared")
    add_files("src/test.rs")
    add_rules("library")
    set_values("rust.cratetype", "cdylib")
    after_load(function (target)
        target:set("shflags", "--crate-type=cdylib", {force=true})
    end)
