name: Commit Norm Checker

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  verify-commit-name:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Commit Norm Checker
        run: |
          commit_msg=$(git log --format=%B -n 1 ${{ github.sha }})
          keyword_regex="^([a-z]+\([0-9A-Za-z_.-]+\)|^[a-z]+): [0-9a-z_.-]+"

          if [[ ! $commit_msg =~ $keyword_regex ]]; then
            if [[ $commit_msg =~ ^Merge\ .* ]]; then
              echo "Skipping merge commit"
            else
              echo $commit_msg
              echo "Commit message does not match Angular convention."
              exit 1
            fi
          fi
        shell: bash
